version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
  chromadb:
    image: chromadb/chroma
  redis:
    image: redis:latest
  supervisor:
    build:
      context: ../packages/supervisor
    environment:
      - SUPERVISOR_PORT=${SUPERVISOR_PORT:-8000}
    ports:
      - "${SUPERVISOR_PORT:-5000}:8000"
    # command removed, entrypoint handles uvicorn
    volumes:
      - ../packages/supervisor:/code
    depends_on:
      - redis
      - postgres
